### ISSUE TITLE
make a plot() method for a loo object

### ISSUE THREAD

**Issue by bgoodri** [jgabry/loo#11]
The plot produced by `print.loo()` with `plot_k = TRUE` is really good but calling it is weird. So, you should make a `plot.loo` method that does that plot and if print.loo is called with `plot_k = TRUE` then call `plot.loo()`.

Also, for values greater than 0.5, the plot should print the observation number next to the point.

**Comment by jgabry** [comment]
Yeah good idea. I can do this later tonight or tomorrow. Should just take a
couple of minutes.

**Comment by jgabry** [comment]
@bgoodri The current develop branch should now do all these things. For printing observation numbers the default is not to do it but setting `label_points = TRUE` will label all k > 0.5 with the indices and any arguments in `...` are passed to text() so you can control the label size, etc, for visibility.

**Comment by bgoodri** [comment]
Great
