### ISSUE TITLE
lx() consumes too much RAM

### ISSUE THREAD

**Issue by bgoodri** [jgabry/loo#14]
Currently,
```
> loo:::lx
function (a, x) 
{
    b <- -a
    bx <- outer(x, b)
    d <- dim(bx)
    k <- .colMeans(log1p(bx), d[1], d[2])
    log(b/k) - k - 1
}
```
stores a giant `bx` matrix in RAM while it works on it one column at a time. Even if it is a bit slower, it would increase the number of situations where `loo` is RAM-feasible if you instead did
```
lx <- function(a,x) {
  a <- -a
  k <- sapply(a, FUN = function(y) mean(log1p(y * x)))
  log(a/k) - k - 1
}
```

**Comment by jgabry** [comment]
Yeah, I was thinking more about speed than memory. But I'd rather have it work in more cases, so this seems like a good call. Thanks, I'll change it now.

**Comment by bgoodri** [comment]
Okay, I got it to work on a state's worth of Census microdata now.

**Comment by jgabry** [comment]
Cool. Thanks for the help with these various memory issues. (I added you as a contributor, which I assume is fine by you. But if for whatever reason you'd rather not be listed I can remove you.)
