### ISSUE TITLE
warn when pareto_k is infinite

### ISSUE THREAD

**Issue by bgoodri** [jgabry/loo#17]
`plot.loo`should throw a warning when some of the shape parameters of the Generalized Pareto distribution are `Inf`. Such points are omitted from the plot, which may give a misleading impression of how robust the estimates are.

**Comment by bgoodri** [comment]
`any(!is.finite(k))` is better than `any(is.infinite(k))` because the
former will also catch NaNs.

**Comment by jgabry** [comment]
Ok great. Thanks. All set.
