### ISSUE TITLE
don't call functions from parallel package if cores=1

### ISSUE THREAD

**Issue by jgabry** [jgabry/loo#19]
This should more easily allow other package authors using **loo** to write tests that run the `loo` function.

**Comment by jgabry** [comment]
@paul-buerkner Hopefully this will resolve that issue where using the parallel package caused errors when you tried to write tests for loo for the brms package. This change will be in the next release (not sure when that will be), but for now it's implemented on the develop branch.

**Comment by paul-buerkner** [comment]
Thanks @jgabry! This will be very helpful to me!
