### ISSUE TITLE
Add warnings to waic

### ISSUE THREAD

**Issue by avehtari** [jgabry/loo#24]
Add warnings to waic corresponding to khat warnings in loo.

**Comment by jgabry** [comment]
Do you mean we should also do some form of psis when computing waic?
Currently we're not doing that, just doing standard waic, which allows the
waic function to run much faster than loo.

**Comment by andrewgelman** [comment]
Hi, I’ll check with Aki but I’m pretty sure we don’t do PISI with WAIC.

**Comment by jgabry** [comment]
Right, that's why I was a bit confused.

**Comment by jgabry** [comment]
Moved to #26
