### ISSUE TITLE
loo crashes on me

### ISSUE THREAD

**Issue by wds15** [jgabry/loo#9]
The waic function works, but loo fails with:

R3.1.3> try({
+     print(loo(log_lik))
+ })
Error in log_lik + psis$lw_smooth : non-conformable arrays
In addition: Warning message:
In mclapply(X = 1:N, FUN = .psis, mc.cores = cores) :
  scheduled cores 3, 4 encountered errors in user code, all values of the jobs will be affected

Any idea? This is loo 0.1.2

**Comment by jgabry** [comment]
Hmm, sorry you're getting an error. Looks like a parallelization issue. If
you do loo(log_lik, cores=1) do you still get an error?

**Comment by wds15** [comment]
Nope, this does not help:

R3.1.3> print(loo(log_lik, cores=1))
Error in if (sigma <= 0) return(rep(NaN, length(p))) : 
  missing value where TRUE/FALSE needed
8: qgpd(p = prb, xi = k, sigma = fit$sigma)
7: FUN(1:1349[[1299L]], ...)
6: lapply(X = X, FUN = FUN, ...)
5: mclapply(X = 1:N, FUN = .psis, mc.cores = cores)
4: psislw(lw, ...)
3: psisloo(log_lik, ...)
2: loo(log_lik, cores = 1)
1: print(loo(log_lik, cores = 1))

**Comment by jgabry** [comment]
Ok, thanks for including the list of calls, very helpful.  I should have
some time later today to look more closely and hopefully I'll get this
sorted out.

**Comment by jgabry** [comment]
I've been unable to replicate this error. Would it be possible to share
your log_lik matrix (email, dropbox, google drive, etc., whatever you
prefer)?

**Comment by wds15** [comment]
Hmm... difficult for me to share this, but it looks like it does not occure
often (at least). In fact I only have a single run which shows this weird
behavour. It looks to me that one on those fits you do returns nothing
usable. Maybe I can figure what is going on.

Sebastian

**Comment by jgabry** [comment]
If you do figure it out or can reproduce it for an example that you can share that would be helpful, but at least it's not giving you this error all the time. 

One of the steps for loo is to fit a generalized Pareto distribution to the tail of the distribution of importance weights. In some cases this can be problematic and so we avoid fitting the Pareto. Most of the problematic weights distributions should get detected by the function and you wouldn't get errors (perhaps warnings), but it's possible you've found an exception. For any of the data points is there a very big difference between the largest and second largest log-weights? (That is, for any of the columns in `lw=-log_lik`)

**Comment by Felipe-Osorio** [comment]
I ran into a similar error after fitting a model via stan_glmer().

**Comment by jgabry** [comment]
@Felipe-Osorio thanks for reporting the error. I assume you're referring to the `stan_glmer` function in the **rstanarm** package that @bgoodri and I are developing? 

It's not clear to me how/if the `loo` function should handle NaNs in the log-likelihood matrix. If the log-likelihood is evaluating to NaN then it's usually an issue that should be dealt with before trying to compute LOO or WAIC or any of the estimates of predictive accuracy. @bgoodri, is there any reason why NaNs in the log-likelihood matrix from `stan_glmer` would be fine to ignore?

**Comment by bgoodri** [comment]
The log likelihood shouldn't evaluate to NaN, if it does evaluate to NaN
the proposal for the parameters shouldn't be accepted, and if it somehow
does get accepted, then it shouldn't be ignored when computing LOO or WAIC.
However, rstanarm evaluates the log-likelihood in R, which may have
different numerical instabilities than Stan does, so NaNs are possible.

**Comment by jgabry** [comment]
In that case this is probably more of an rstanarm issue than a loo issue. I
think loo probably shouldn't accept a matrix with any NaNs, as it wouldn't
be clear why they were there since loo is agnostic about how the matrix was
obtained.

**Comment by Felipe-Osorio** [comment]
Thanks for clearing that up. I'll shift the discussion to stan_glmer with a reproducible example.
